### ISSUE TITLE
Tcp Port

### ISSUE THREAD

**Issue by ebal** [PhotoBackup/client-android#1]
You are using the default tcp port 8080 on the photobackup server instance.
Although the use must have the ability to change it to something else through the settings menu.

8080 is the default tcp port for a lot of projects as it is the HTTP Alternate  by IANA

Thanks in advance

**Comment by stephanepechard** [comment]
I planned to use the 8420 TCP port. The Android client does not specify any TCP port for the transmission, the user has eventually to add it to the server address.

**Comment by ebal** [comment]
I've tried that, but i got an error from android-client.
Has this moment being implemented ?
Can I use something like this: 192.168.1.11:8420 ?
Thanks in advance

**Comment by stephanepechard** [comment]
Ok, I should test this particularly. I don't remember to having done this...
You can't use the port 8420 right now, I didn't commit it already. I'm breaking things a bit at the moment... ;-)

**Comment by stephanepechard** [comment]
You can now use the 8420 port with the last version of photobackup-bottle server.
Hope it will simplify things for you.
