### ISSUE TITLE
Filter the Upload journal

### ISSUE THREAD

**Issue by white-gecko** [PhotoBackup/client-android#10]
This is a feature request.

It would be cool, if its possible to use the legend"(green) Backed up (orange) Waiting (rad) Error" to filter the list by pressing those categories. This way it would be easier to inspect, which uploads failed and similarly.

**Comment by stephanepechard** [comment]
That's actually a great idea! I will try to see what's possible around this. Thanks for the suggestion!

**Comment by stephanepechard** [comment]
Done in ca8012cf09fc5b6b489be480a4792ad17fba5c18

**Comment by white-gecko** [comment]
You mean in ac3f9285095bd2e404f21567d4659e3dd2979811 and 43214813018f9014b93044f81637be01452bf28a ;-)

Thank You

**Comment by stephanepechard** [comment]
You're right, sorry. The ca8012cf09fc5b6b489be480a4792ad17fba5c18 commit is the one of corresponding release.
Thanks for your attention!

**Comment by white-gecko** [comment]
Just added it for the correct semantic connection :-D
