### ISSUE TITLE
Support for HTTP auth

### ISSUE THREAD

**Issue by pmaziere** [PhotoBackup/client-android#12]
I always protect my self hosted services behind an HTTP auth.
While the server does not support HTTP authentication for now, that would be nice if the android client could add support for HTTP auth.
thanks

**Comment by stephanepechard** [comment]
I've planned to enhance server capabilities in a (maybe not so) close future.
Thanks for the suggestion, I'll add it to my list.

**Comment by pmaziere** [comment]
here is a patch to implement basic http auth in photobackup android client
[add-basic-http-auth.txt](https://github.com/PhotoBackup/client-android/files/57413/add-basic-http-auth.txt)

**Comment by stephanepechard** [comment]
Available in version 0.8.0

**Comment by pmaziere** [comment]
thanks
