### ISSUE TITLE
Android Client V0.8.0 refuses to upload image

### ISSUE THREAD

**Issue by mr337** [PhotoBackup/client-android#18]
Finally got time to give this a go. I have setup both the go and python version of the sever and having issues communicating with the client.

I have a setup like so:
Client -> LAN -> Nginx -> Python or Go Server

Since I have a background in python I decided to starting debugging it. I decided to use Werkzeug debugging middleware and start following the different calls to the server. So far the only calls that the Android client is sending is just the POST to /test. Which the app says "Server configuration is valid, great!".

From there I can confirm the client attempts to upload an image but fails giving no error. I do not see any traffic on the server. I can manually post to the server with success

```
$ http -f post http://starbuck/ password='REDACTED' filesize=18709 upfile@/tmp/blah.png
```

This results in a 200 and image being written to disk. When I try again with the client I get this this

```
127.0.0.1 - - [31/Dec/2015 00:32:25] "POST / HTTP/1.0" 200 0  <--- My manual post via httpie
127.0.0.1 - - [31/Dec/2015 00:38:23] "POST /test HTTP/1.0" 200 0  <--- Turning on the client service
```

And no more requests when I take another image via the client.

I have also tried the python-client and it works great:

```
$ ./photobackup.py upload http://starbuck/ /tmp/blah.png
The server password: 
Request was successful!
```

On the Android client I have the server set to `http://starbuck/`, entered my server password and do not have HTTP Auth enabled. Is there something I am missing?

**Comment by stephanepechard** [comment]
Please try with the last 0.9.0 version, I changed the upload library.

**Comment by stephanepechard** [comment]
@mr337 did you try with the latest version? (the 0.11 should soon be available)
I'll probably close this issue without more info.

**Comment by mr337** [comment]
@stephanepechard I have not :( busy with life. If you think this is all wrapped up I'll close this.

**Comment by stephanepechard** [comment]
Thanks @mr337
