### ISSUE TITLE
The network choosing UI is not self explanatory.

### ISSUE THREAD

**Issue by Zegnat** [PhotoBackup/client-android#2]
“Used network” doesn’t make sense as a checkbox label, I feel. I had to toggle it a view times to actually understand what it was meant to do. Maybe calling it “Back-up on Wi-Fi only” would make more sense and instantly describes what the checkbox does?

I took a look at some other apps on my phone and saw that most of them handle this is different ways. But never with a checkbox, as a checkbox represents an on/off state and not a choice. WhatsApp lets me configure what it downloads per connection (separate settings for mobile, Wi-Fi, and roaming), Flickr’s Auto-Uploadr (not a typo) displays radio buttons to make it clear my choice is between “Wi-Fi only” and “Mobile/Wi-Fi”.

Would love to see this part of the interface become more self explanatory!

![Screenshots showing WhatsApp’s and Flickr’s network settings UI.](https://cloud.githubusercontent.com/assets/490579/8722784/6424a646-2bc8-11e5-8d92-09d095dbd0cc.png)

**Comment by stephanepechard** [comment]
You're right, it's not clear enough. I have to think a bit about how I will handle this though. WhatsApp's option is maybe too complicated for a simple app like PhotoBackup, plus it doesn't handle videos. I like the Google Photos' way of doing, it's radio buttons like Flickr but in a modal window:

![screenshot_2015-07-16-17-23-38](https://cloud.githubusercontent.com/assets/703194/8727376/9e99bff2-2bdf-11e5-90d7-c6d7a43933f6.png)

**Comment by Zegnat** [comment]
I don’t use Google Photos, and didn’t want to activate the whole thing and link it to my account just for the screenshot. Have to say I like their solution. Flickr’s options are very sparse – text wise – and I think Google has exactly the right amount of text to explain what the option is for.

Would love to see that land!

**Comment by stephanepechard** [comment]
Done, should be available on Google Play in a few hours.
Thanks for your input! Feel free to share your views on the app and what can be done.

**Comment by Zegnat** [comment]
I’m gonna wait for the update through F-Droid, I think, that’s where I found the app in the first place. In the mean time, I am going to get started on a PHP server implementation.

**Comment by stephanepechard** [comment]
Code is now updated on github, I just don't know how long it will take to get to F-Droid.
A PHP implementation would be great, thanks. I created a repo you can use for that: https://github.com/PhotoBackup/server-php

**Comment by Zegnat** [comment]
Just got back from a trip and found 0.6.2 on F-Droid. The updated UI works completely fine for me! I have also been using my own server implementation for the last few weeks and it is working fine, so I’ll try to get it on the official repo this week. Based it on the [API](https://github.com/PhotoBackup/api), but that raml file needs more documentation in there 😶

**Comment by stephanepechard** [comment]
It's great to hear about your implementation.
I know the API is very minimal, I need to spend some time on a bit of documentation some day.
