### ISSUE TITLE
Upload journal not refreshing

### ISSUE THREAD

**Issue by fliker09** [PhotoBackup/client-android#21]
I have to select/unselect one of the Saved/Waiting/Error buttons in order to refresh the journal. Is that OK?

**Comment by stephanepechard** [comment]
Yes, this is the expected behavior. Each button is a toggle to show/hide the selected category.
I agree the Android toggle button is not very clear...

**Comment by fliker09** [comment]
If I remember it right in older versions, without buttons, upload journal was self-refreshing (which is more convenient)

**Comment by stephanepechard** [comment]
Fixed in b23fddd6551332059c8a57986032460af2aebd64
