### ISSUE TITLE
Handling of already uploaded images (status code 409)

### ISSUE THREAD

**Issue by zealot128** [PhotoBackup/client-android#24]
According to the API spec, the server should respond with a 409 conflict status code, if an image is already uploaded.
Unfortunately, there is no handling code for that case at the moment, so that images will always stay as "error"

Maybe it is possible to change in https://github.com/PhotoBackup/client-android/blob/master/src/fr/s13d/photobackup/PBMediaSender.java#L168 and check for that error code? In that case, maybe handling the upload as "success" would be a good option.
What do you think?

**Comment by stephanepechard** [comment]
Damn, you're right. I should check on that. Thanks!
