### ISSUE TITLE
Remove 'Stop the service' action in the notification

### ISSUE THREAD

**Issue by stephanepechard** [PhotoBackup/client-android#41]
From gitter:

@zealot128
I have another question/propasal: From the notification one can stop the service. Is this useful? Maybe then I will forget to renenable the upload later on.

@stephanepechard
I don't know if it's useful, it's true I don't use it, but some people may forget they have the service running in background so I thought they could easily stop it from here
it's just an option, you can open the activity without stopping the service
but I agree it may be misunderstood

@zealot128
the notification is ok - If the user wants to stop, he can click the service and stop then. Stopping is not a very often used action, in my opinion, and only bloats the notification. I think, I even stopped the service accidently
maybe it is misunderstood in the way "Stop the current upload (Because I am not in a good wifi...)"

@stephanepechard
yeah you're right

@zealot128
because the user does not know what a "Service" means in this context

@stephanepechard
true
I open an issue for it

**Comment by stephanepechard** [comment]
This one was easy :-)

**Comment by zealot128** [comment]
Nice :)

In a (maybe not very close) future, I can imagine a "pause upload"/"Stop current upload" or similar as replacement, like I am just on the some wifi which I know isn't very fast, or there is a Wifi which required registration, so download will fail anyways etc...

**Comment by stephanepechard** [comment]
Yes, it would be more meaningful.
We should keep this commit in mind to see how it is done.
