### ISSUE TITLE
Upload only photos from specified folders

### ISSUE THREAD

**Issue by jkufner** [PhotoBackup/client-android#48]
I have few web pages and an icon set with few hundred small icons stored on my SD card. I guess you have a good idea what happend during initial backup. Yes, all these irrelevant pictures got copied along with my photos...

The client should backup only selected folders. There is no need to backup everything else. There should be list of the folders in the settings, however, defaults should be easy to detect (the DCIM folders). Also USB-OTG storages should be ignored.

**Comment by stephanepechard** [comment]
Even better, there's a PR for that: #29

**Comment by stephanepechard** [comment]
Done in v0.10.0. This is a first version, it is probably not perfect. Any feedback is welcomed!

**Comment by jkufner** [comment]
Awesome! Thank you.
