### ISSUE TITLE
resume mode, do not re-upload everything...

### ISSUE THREAD

**Issue by psychedelys** [PhotoBackup/client-android#5]
When I stopped the service, and the re-enabled it, it start to repush all pictures.... BUt the auditlogs are correct. Would it be possible to skip this re-upload, as sometimes I am on really slow and limited wifi.

let's imagine a "force/check" box, which when enable, act as now. If not enabled, just retry what is not success in the audit-log.

Might also want a full re-checked button.

does that make sense?

Thanks for the Android client, by the way.

**Comment by stephanepechard** [comment]
What you describe is strange to me. This is not the expected behavior. You should be able to start or stop the service without repushing pictures that are already on your server.
The list of uploaded files is stored on Android disk, so everything is pushed again only if you erase the application.
I have a few questions to try to identify the problem: What is your device/OS? is your device rooted? and what do you call auditlogs?
Thanks for your help on this bug.

**Comment by psychedelys** [comment]
oneplus 1, last release meaning 5.1.1 officals. and no, the device is not rooted.

Ok, sorry my un-precise description, the auditlog = the journal stuff that I see when the service is launched, so the one store ion the disk.
I am using my own photobackup server (https://github.com/psychedelys/photobackup-server-flask) but I do not think that the problem... 

OK, so It might be the problem, that for some of the picture, the journal logs shows the files in orange, but are already on the server side. I got some instabilities in the app, so might have been the problem that the log was at some point damaged. I got some files, which are push, minus I am sure they were green 2/3 days ago.

Please feel free to tag-it as not reproducible and close-it. I do not know yet, how to debug a android app crash.

**Comment by stephanepechard** [comment]
I don't have much time for it at the moment. What I can propose you is not to use this server implementation, as it is not maintained anymore.
If you want to stick with Python, please use: https://github.com/PhotoBackup/server-bottle
which is the official Python server implementation. I ditched the Flask one a few weeks ago.
It may cause some problems if there are inconsistencies between server and app.

**Comment by stephanepechard** [comment]
It's not really a resume mode, as it does not communicate with the server on the state of the upload, but [version 0.7.0](https://github.com/PhotoBackup/client-android/releases/tag/v0.7.0) allows to specify you do not want to reupload all your pictures, but just the newly taken.
