### ISSUE TITLE
Cannot select folders for sync before enabling the service

### ISSUE THREAD

**Issue by jkufner** [PhotoBackup/client-android#51]
If I enable the service before limiting the folders to sync, all images get enqueued and uploaded anyway. The list must be accessible before enabling the sync and once the list is changed, the queue should be repopulated and filtered using the new rules.

**Comment by stephanepechard** [comment]
I know the limitation but this first version is like this. Modifying it
induce some refactor with impact I should evaluate first.
Thanks for your input

**Comment by stephanepechard** [comment]
Done in 0bccfb26fbed0a0c6934a1c5a6a6ed641fe4f974 and 08957b20d8a8aa9d5f9cfa7bbc04f4f354117834 for version [0.10.1](https://github.com/PhotoBackup/client-android/releases/tag/v0.10.1)
