### ISSUE TITLE
Choose what folder to search pictures?

### ISSUE THREAD

**Issue by Mistress-Anna** [PhotoBackup/client-android#7]
It could be nice if there was an option to specify in which folder should picture files be looked for upload

**Comment by stephanepechard** [comment]
That could be handful, but it is not something easy to do, both technically and ergonomically.

Technically, PhotoBackup relies on the underlying MediaStore library, that does not know any particular folders but consider pictures on the whole disk storage. Introducing folder considerations would add a layer of complexity that is not easy to maintain.

Ergonomically, adding, removing, handling a list of folders to be looked for upload would break the simplicity of the current interface. A good thinking of it is necessary before doing it.

At this moment, it is a feature that is not planned to be done. It may change in the future though. Sorry.

**Comment by zealot128** [comment]
I think it would be interesting, as now, PhotoBackup will upload all pictures people send to me with various messengers like WhatsApp. So my uploaded folder is spammed with "funny pics" and stuff like this :)

Maybe a simple Radio button setting, like the WiFi, will suffice? (e.g. "Only upload photos from camera", "Upload all pictures on that device")

I will try to dig into the MediaStore!
